// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_TfHJG-r-rB3rcmw-JlygsHFzc7-mo44',
    appId: '1:171349781146:web:e6aca81b3d7def83544d23',
    messagingSenderId: '171349781146',
    projectId: 'college-canteen-35181',
    authDomain: 'college-canteen-35181.firebaseapp.com',
    storageBucket: 'college-canteen-35181.firebasestorage.app',
    measurementId: 'G-EMBDBE6FTX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAipzWG8Ckp5JtxmZ9toVjByQ2QovO75BU',
    appId: '1:171349781146:android:6f60632cab7e70f3544d23',
    messagingSenderId: '171349781146',
    projectId: 'college-canteen-35181',
    storageBucket: 'college-canteen-35181.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFgUpT-gWpFyzGHNbfXN_ayjFvPLzAWZU',
    appId: '1:171349781146:ios:c126b253dce171f8544d23',
    messagingSenderId: '171349781146',
    projectId: 'college-canteen-35181',
    storageBucket: 'college-canteen-35181.firebasestorage.app',
    iosBundleId: 'com.example.collegeCanteen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFgUpT-gWpFyzGHNbfXN_ayjFvPLzAWZU',
    appId: '1:171349781146:ios:c126b253dce171f8544d23',
    messagingSenderId: '171349781146',
    projectId: 'college-canteen-35181',
    storageBucket: 'college-canteen-35181.firebasestorage.app',
    iosBundleId: 'com.example.collegeCanteen',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_TfHJG-r-rB3rcmw-JlygsHFzc7-mo44',
    appId: '1:171349781146:web:2092d6218802a917544d23',
    messagingSenderId: '171349781146',
    projectId: 'college-canteen-35181',
    authDomain: 'college-canteen-35181.firebaseapp.com',
    storageBucket: 'college-canteen-35181.firebasestorage.app',
    measurementId: 'G-7YCE4THD5Z',
  );
}
